/**
 * Arabic text cleaner for PDF-extracted text.
 *
 * Handles the common issues caused by Poppler pdftotext and pdf-parse
 * when extracting text from Arabic PDFs generated by MEN.gov.ma:
 * 1. Bidi control characters (LRM, RLM, RLE, RLO, LRE, LRO, PDF, FSI, LRI, RLI, PDI)
 *    that cause visual ordering artifacts in the extracted text
 * 2. Broken Alef+Lam letter joining (e.g. "بالغ" → "بلاغ", "الرتبية" → "التربية")
 * 3. Tatweel (kashida U+0640) removal
 * 4. Normalization of extra whitespace and blank lines
 *
 * IMPORTANT: Many Arabic PDFs (including MEN.gov.ma circulars) store text
 * WITHOUT spaces between Arabic words (relying on the PDF renderer to add them).
 * This cleaner does NOT attempt to insert word boundaries — it only fixes
 * the character-level corruption and broken joining.
 */

// All bidi control characters
const BIDI_CONTROLS = /[\u200e\u200f\u202a-\u202e\u2066-\u2069]/g;

/**
 * Fix common Arabic letter joining errors in PDF-extracted text.
 * These patterns are reliably broken in MEN circulars.
 */
function fixBrokenJoining(text: string): string {
    let s = text;

    // Specific MEN circular patterns (apply in order, specific first)
    s = s.replace(/بالغ/g, "بلاغ");                   // "بلاغ صحفي"
    s = s.replace(/الرتبية/g, "التربية");            // وزارة التربية الوطنية
    s = s.replace(/املعطيات/g, "المعطيات");
    s = s.replace(/املادية/g, "المادية");
    s = s.replace(/املوقع/g, "الموقع");
    s = s.replace(/االلكرتوين/g, "والكرتوين");       // كلمة "الكرتوين"
    s = s.replace(/املالحظات/g, "الملاحظات");
    s = s.replace(/وامللاحظات/g, "والملاحظات");

    // Generic Alef-Lam fixes (apply after specifics)
    s = s.replace(/وامل/g, "وال");                   // Waw+Alef+Lam
    s = s.replace(/واملال/g, "والمل");               // Waw+Alef+Mim+Alef+Lam
    s = s.replace(/اامل(?=[^\u064b-\u065f\u0670\s\n])/g, "ال"); // Mim+Alef+Lam
    // Double-alef from bidi extraction: insert the missing Alef to restore natural "ال" article
    // e.g. "االستشارات" -> "الاستشارات" (not "الستشارات")
    s = s.replace(/اال(?=[\u0600-\u06ff])/g, "الا");

    // Compound alif forms
    s = s.replace(/األ/g, "الأ");
    s = s.replace(/اإل/g, "الإ");
    s = s.replace(/اآل/g, "الآ");

    // "املال" → "ال" (Alef+Mim+Alef+Lam — "المل...")
    s = s.replace(/املال(?=[^\u064b-\u065f\s\n])/g, "ال");

    // "اما" → "ال" before diacritics (Alif+Mim+Alef with tashkil)
    s = s.replace(/اما(?=[\u064b-\u065f\u0670])/g, "ال");

    // Remove Tatweel/Kashida
    s = s.replace(/\u0640/g, "");

    return s;
}

/**
 * Main Arabic text cleaner.
 * Processes text extracted from PDFs to produce clean, readable Arabic.
 */
export function cleanArabicExtractedPdf(text: string): string {
    if (!text) return "";

    let s = text;

    // Step 1: Strip ALL bidi control characters
    s = s.replace(BIDI_CONTROLS, "");

    // Step 2: Fix broken Arabic letter joining
    s = fixBrokenJoining(s);

    // Step 3: Clean whitespace
    s = s
        .split("\n")
        .map((line) => line.trim())
        .filter((line, i, arr) => line !== "" || (i > 0 && arr[i - 1] !== ""))
        .join("\n");
    s = s.replace(/\n{3,}/g, "\n\n");
    s = s.trim();

    return s;
}

/**
 * Legacy alias for backwards compatibility.
 * @deprecated Use cleanArabicExtractedPdf directly
 */
export const cleanArabicText = cleanArabicExtractedPdf;
