ALTER TABLE "Settings" ADD COLUMN "fallbackProvider" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Settings" ADD COLUMN "fallbackModel" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Settings" ADD COLUMN "fallbackApiKey" TEXT NOT NULL DEFAULT '';
